## GitHub composite workflow to setup Nim - for nmostr.
# Copyright © 2023 Gruruya <gruruya.chi4c@slmails.com>
# SPDX-License-Identifier: AGPL-3.0-only

name : Nim run
description: 'Run shell commands in an environment with Nim.'
## See also:
## * https://github.com/marketplace/actions/setup-nim-environment
## * https://github.com/marketplace/actions/run-on-architecture

inputs:
  run:
    description: 'Commands to run'
    required: true
  version:
    description: 'Version of Nim.'
    required: false
    default: 'stable'
  token:
    description: 'Your GitHub token.'
    required: false
  arch:
    description: 'Architecture to build Nim for.'
    required: false
    default: 'x86_64'

runs:
  using: "composite"
  steps:
    - name: Get Date
      if: ${{ inputs.arch == 'x86_64' || inputs.arch == 'x86' }}
      id: get-date
      run: echo "date=$(date "+%Y-%m-%d")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache choosenim
      if: ${{ inputs.arch == 'x86_64' || inputs.arch == 'x86' }}
      uses: actions/cache@v3
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ inputs.version }}-${{ steps.get-date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-choosenim-${{ inputs.version }}-

    - name: Cache nimble
      uses: actions/cache@v3
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-${{ inputs.arch }}-nimble-${{ hashFiles('*.nimble') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.arch }}-nimble-

    - name: Setup Nim
      if: ${{ inputs.arch == 'x86_64' || inputs.arch == 'x86' }}
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ inputs.version }}
        repo-token: ${{ inputs.token }}

    - name: Run
      if: ${{ inputs.arch == 'x86_64' || inputs.arch == 'x86' }}
      shell: bash
      run: ${{ inputs.run }}

    - name: Setup Nim for ${{ inputs.arch }} and Run
      if: ${{ inputs.arch != 'x86_64' && inputs.arch != 'x86' }}
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{ inputs.arch }}
        distro: ubuntu_devel
        githubToken: ${{ inputs.token }}

        dockerRunArgs: |
          --volume "$HOME/.nimble:/root/.nimble"

        install: |
          apt-get update -q -y
          apt-get install -q -y nim

        run: |
          export PATH="$PATH:${NIMBLE_DIR:-$HOME/.nimble}/bin"
          ${{ inputs.run }}
