## Documentation GitHub workflow - for nmostr.
# Copyright © 2023 Gruruya <gruruya.chi4c@slmails.com>
# SPDX-License-Identifier: AGPL-3.0-only

name: documentation

on:
  push:
    paths: ['.github/workflows/documentation.yml', '.github/workflows/nim-run/action.yml', 'src/**']
    branches: master

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nim, then generate docs
      uses: './.github/workflows/nim-run'
      with:
        run: nimble doc -y --project src/nmostr.nim --outDir:htmldocs
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: ln -s nmostr.html htmldocs/index.html

    - name: Setup HTML for GitHub Pages
      uses: actions/configure-pages@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Docs
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'htmldocs'

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
